### ISSUE TITLE
Can't change the display of the value immediately.

### ISSUE THREAD

**Issue by j010wdz** [jsdf/react-native-htmlview#10]
Hi,
     When I set value which from 'this.props'. It shows the last value I set.

**Comment by oillamp** [comment]
i have the same question. i use it as a part of a cell in listview, when i request api and update datasource, the htmlview would not update, it show the last value i set.

**Comment by richchurcher** [comment]
@j010wdz @oillamp can you confirm that this is still an issue with the latest version (0.10)?
