### ISSUE TITLE
Comments <!-- comment --> generating a lot of line breaks

### ISSUE THREAD

**Issue by pzehle** [jsdf/react-native-htmlview#100]
I'm parsing html code from an API. Everything is going ok, but I get a new line break every time the module finds a comment, like it tries to render it like a `p` or `span`. Is there a workaround to avoid this behavior?

**Comment by richchurcher** [comment]
This is likely related to #35 , and it's not limited to comments. For example,
```
    <HTMLView value={`Hello.<!-- comment -->Foo.<strong>Bar.</strong><em>Wombat.</em>`} />
```
will render as:

Hello.
Foo.
**Bar.**
*Wombat.*

One workaround until we can improve this behaviour would be to wrap the HTML you're trying to render in a block level element. For example:
```
    <HTMLView value={`<div>Hello.<!-- comment -->Foo.<strong>Bar.</strong><em>Wombat.</em></div>`} />
```

**Comment by pzehle** [comment]
Hey! I'm going to try this and I'll keep you posted.

Thanks for the response.

**Comment by richchurcher** [comment]
Consolidating this issue at #114 .
