### ISSUE TITLE
can't change default color

### ISSUE THREAD

**Issue by csomakk** [jsdf/react-native-htmlview#101]
Hi! I'm not setting color in html but, I'd like to set id for all text, outside.
Any idea?
Cheers

like:
                <HTMLView
                    value={shortText}
                    stylesheet={htmlStyles}
                    style={{
                        color: "white"
                    }}
                />

**Comment by csomakk** [comment]
thinking 
<Text key={index} style={parent ? opts.styles[parent.name] : null}> could have a default instead null?

**Comment by vitormalencar** [comment]
Any update about this?

**Comment by richchurcher** [comment]
@csomakk You can change the style (or other props) of the underlying `Text` component like so:

```
  const componentStyles = StyleSheet.create({
    color: 'orange'
  })
  const htmlStyles = StyleSheet.create({
    a: {
      color: 'green'
    }
  })
  const content = `I should be orange. <a href="">I should be green.</a>`
  <HTMLView
    stylesheet={htmlStyles}
    textComponentProps={{ style: componentStyles }}
    value={content} />
```

**Comment by base0225** [comment]
<HTMLView
        stylesheet={htmlStyles}
        textComponentProps={{ style: {color:'orange'} }}
        value={content} />
