### ISSUE TITLE
Support regex tags

### ISSUE THREAD

**Issue by G2Jose** [jsdf/react-native-htmlview#102]
Related to https://github.com/jsdf/react-native-htmlview/issues/70. 

Currently it seems like keys in the param for `StyleSheet.create` only take simple strings (`'div'`, `'a'` etc). It would be really useful to support regex in order to be able to match multiple tags (Eg: something like `'.'` to match all tags).

**Comment by richchurcher** [comment]
We can now style the entire HTMLView using `textComponentProps` (see updated documentation). Given this, a wildcard style is probably unnecessary. Please feel free to open another issue/PR if you feel strongly about it.
