### ISSUE TITLE
Styles don't seem to cascade

### ISSUE THREAD

**Issue by G2Jose** [jsdf/react-native-htmlview#103]
It seems like styles applied to a tag currently do not cascade to child tags. I have a problem similar to https://github.com/jsdf/react-native-htmlview/issues/70, but the solution presented there does not seem to work. 

I have an API that returns strings that sometimes have html tags, and sometimes do not. I want to style all text returned in the same way (same `fontSize`). I tried wrapping all text in a `<styledHTML>` tag, and specified styles for it, but it seems like nested tags within this do not have the same style. 

Ex:
```
const wrapContent = (str) => `<styledHTML>${str}</styledHTML>`;

const htmlContent1 = wrapContent('Hello');
const htmlContent2 = wrapContent('<p>Hello</p>');
```

I have my stylesheet defined as
```
const style = StyleSheet.create({
  styledHTML: {
    fontSize: 16,
  },
});
```
Now when I display this in `HTMLView`, only one of them has the right styling:
```
// Has right styling
<HTMLView
  value={htmlContent1}
  stylesheet={style}
/>
```
```
// Does not have right styling, since the text is wrapped in a <p>, inside <styledHTML>
<HTMLView
  value={htmlContent2}
  stylesheet={style}
/>
```

**Comment by richchurcher** [comment]
@G2Jose You shouldn't need to do this now that you can pass a `style` prop via `textComponentProps`. You're correct that cascading is not working as yet, but there are several proposals to make that happen :smile:
