### ISSUE TITLE
IOS error: RCTJSONStringify() encountered the following error: Invalid type in JSON write (NSError)

### ISSUE THREAD

**Issue by lihjay** [jsdf/react-native-htmlview#105]
I am running in the IOS, the following error:
RCTJSONStringify() encountered the following error: Invalid type in JSON write (NSError)

some page can loaded,but some page can't loaded.
Is it because some long html causes this error??

**Comment by jsdf** [comment]
I haven't run into that error but that seems like a possibility

**Comment by Tarkzeng** [comment]
I had catch the same error but not NSError:
RCTJSONStringify() encountered the following error: Invalid type in JSON write (**NSURL**)

@lihjay   Have you solved it?

**Comment by richchurcher** [comment]
@lihjay or @Tarkzeng can you post a minimal example (preferably in a repo somewhere) using the latest `react-native-htmlview` which reproduces the problem? Cheers!

**Comment by richchurcher** [comment]
Closing for now, please feel free to submit another issue if this continues to be a problem with the latest version.
