### ISSUE TITLE
<li> subsequent list items do not wrap to the next line

### ISSUE THREAD

**Issue by emik** [jsdf/react-native-htmlview#106]
Is anyone else having this issue?

![react native li](https://cloud.githubusercontent.com/assets/2894097/26419413/972ad0e6-40b7-11e7-88e2-a769d09042a9.PNG)

Styling with flex doesn't seem to do anything. Source html for the image: 

`<ul><li>test1</li><li>test2</li></ul>`

**Comment by emik** [comment]
Didn't realise that it takes into account \n text line breaks to implement them

**Comment by steoo** [comment]
Yes, the problem is that if `lineBreaks={false}` is set `<li>`'s are inlined, if `lineBreaks={true}` `<p>`'s has big lineBreaks. Any idea on how to handle this?

**Comment by steoo** [comment]
Solved settings `paragraphLineBreak={""}`, basically I removed it.

**Comment by tkserver** [comment]
Hey @steoo I've had a problem with line breaks and paragraphs together making huge gaps between paragraphs.  Did paragraphLineBreak={""} fix that for you?

**Comment by steoo** [comment]
Yes it did, not exactly a solution but a workaround. Another problem you may encounter is rendering of `<br>`, to fix that you can do something like this in the `renderNode`


```
renderNode() {
  if (node.name === "br" && node.parent.name === "li") {
    return (
      <Text key={index} style={{margin: 0}}/>
    )
  }
}
```

**Comment by tkserver** [comment]
Thanks @steoo 
What I ended up doing was removing \n from the api, which helped.  But sometimes users do line breaks and sometimes paragraphs and so on.

**Comment by tkserver** [comment]
Hello @steoo I implemented this but no change.  Where did you do this the paragraphLineBreak?

```
                  <HTML
                    {...DEFAULT_PROPS}
                    ignoredStyles={['font-family', 'letter-spacing']}
                    paragraphLineBreak={""}
                    html={content}
                  />
```

**Comment by steoo** [comment]
what `DEFAULT_PROPS` contains? What's the value of `LINE_BREAKS`?
