### ISSUE TITLE
How is this different/better than the official WebView component? 

### ISSUE THREAD

**Issue by dijonkitchen** [jsdf/react-native-htmlview#109]
Looks like React Native's WebView component can render HTML too: 
https://facebook.github.io/react-native/docs/webview.html#source

**Comment by peterpeerdeman** [comment]
This component parses html and converts the tags to native components, which is very lightweight performance wise. The React Native WebView renders the html in a webview component which will render the html as a browser would (with css styling and all) and is a much heavier component in your view, performance wise.

**Comment by dijonkitchen** [comment]
Got it, thanks!
