### ISSUE TITLE
this.setState() won't trigger a re-render of HtmlView

### ISSUE THREAD

**Issue by pedrodevoto** [jsdf/react-native-htmlview#11]
If I set the value prop to some state variable and then set that variable through setState() function, the HtmlView does not get refreshed with the new value. Haven't had much time to check the source for myself.

**Comment by pedrodevoto** [comment]
Fixed it by commenting out line number 76 on HTMLView.js.

```javascript
...
componentWillReceiveProps() {
  // if (this.state.element) return
  this.startHtmlRender()
},
...
```

I don't know yet if I broke something else by doing so.

**Comment by sf577** [comment]
Ive issued a Pull Request so this now works, hopefully this will be merged in

**Comment by pedrodevoto** [comment]
Working fine with new merge

**Comment by WhatAKitty** [comment]
@sf577 @pedrodevoto  I have this problem and not working fine in new version: 4.1.
