### ISSUE TITLE
why the width style attr is not working 

### ISSUE THREAD

**Issue by xsgkaka** [jsdf/react-native-htmlview#113]
like this :
`htmlstr = "<aaa>{'hello'}</aaa>";`
 styles:
`aaa:{
 width:300,
backgroundColor:"red"
}`
but width  prop is not working.

**Comment by richchurcher** [comment]
@xsgkaka By default the `Text` component is used: this does not support styling of height and width (see https://facebook.github.io/react-native/docs/text.html#style for a list of available styles). You can now pass in a component to use in place of `Text` which might allow more flexibility (see updated docs for `TextComponent` and `NodeComponent`).
