### ISSUE TITLE
img tags canot show

### ISSUE THREAD

**Issue by cmideal** [jsdf/react-native-htmlview#12]
why img cannot show

**Comment by dukedom** [comment]
I also encounter the problem

**Comment by zivchen** [comment]
Same here
this tag doesnt show anything
<p><a href="http://www.ktuvit.com/view.php?id=19612&amp;m=subtitles&#35;9612" title="צער גידול בנות עונה 5, פרק 6: The Legend of Ranger Joe | 1991"><img style="margin-left: 10px;border:0;" src="http://www.ktuvit.com//contents/series/seasonimages/thumbnails/thumb_337.jpg" width="100" height="144" align="right" /></a>In this episode, Joey hits a string of great luck! He gets free cable, concert tickets and job interviews, he even gets a date with a hot girl, but then his luck runs short when his interview comes along. Michelle learns to tap and really annoys Stephanie, who taught her to tap. She annoys her so much that one day the shoes go missing...who do you think took them? Jesse debates what to name his twins, when they are born, and accidentally reveals to DJ that he has a secret about his past. We later find out that he got his name changed in kindergarten.</p>

**Comment by phil-allcock** [comment]
I have been trying to get the same thing to work. According to [the docs](https://facebook.github.io/react-native/docs/text.html#nested-views-ios-only), nested views are only supported on ios. Which means that it won't work for android with images that wrapped inside text nodes such as "a" tags.

**Comment by richchurcher** [comment]
Correct. I guess one possibility would be to pass in something else in place of `Text` via the `TextComponent` prop (see updated docs).
