### ISSUE TITLE
fail to install react-native-htmlview

### ISSUE THREAD

**Issue by RazerTang** [jsdf/react-native-htmlview#128]
When i  type 'npm install react-native-htmlview --save' command in my terminal,it shows like  below,and i found plenty of packaes were removed.how can i sove  this  problem?
react-native-cli:v2.0.1
react-native:v0.46
nodejs:v8.1.4
![2017-07-15 6 19 52](https://user-images.githubusercontent.com/5905640/28238631-8e01d3a6-698a-11e7-829a-1e6d692b63fa.png)

**Comment by richchurcher** [comment]
This is more than likely due to npm 5, which comes with Node 8 and represents a breaking change for some packages. I'll investigate further, but you can probably just use Yarn if you're comfortable with that:
```
yarn add react-native-htmlview
```

**Comment by richchurcher** [comment]
Actually @RazerTang there are a number of known issues with npm 5 it seems. Can you please try rolling back to v4 with:
```
npm install -g npm@4
```
and see if it solves your problem? It would probably be wise to entirely remove `node_modules` for your project too.

**Comment by RazerTang** [comment]
finally I use npm version 4 sovle this problem.thanks @richchurcher

**Comment by richchurcher** [comment]
Awesome!
