### ISSUE TITLE
react-native 41

### ISSUE THREAD

**Issue by johntom** [jsdf/react-native-htmlview#129]
If I load 
import HTMLView from 'react-native-htmlview';

results in the following when bringing up app
Unable to resolve module prop-types from /Users/Mike/NSP6/NSP6-BB2/node_modules/react-native-htmlview/HTMLView.js:

**Comment by richchurcher** [comment]
Hrm. Without more details, I would suggest trying this (assuming MacOS or Linux):
```
rm -rf node_modules && yarn install && yarn start --reset-cache
```
Be sure to stop the RN packager from running first. Substitute `npm` for `yarn` if you're not using Yarn. The `prop-types` module is React externalising proptypes, and it should be brought in by `react-native-htmlview` via its `package.json`, but maybe something's screwy with your local install.

**Comment by johntom** [comment]
Hi,
I am on a mac and did the above (rm -rf node_modules && yarn install && yarn start --reset-cache) suggestion which caused an upgrade issue that cause my app to fail and it took me a while to track down but was happy that I was able to figure it out. I still get the same error and currently using Webview although I perfer your component.
J

**Comment by bsonntag** [comment]
@johntom try `yarn add prop-types` and then restart the packager with `yarn start --reset-cache`.

As an extra tip, to prevent upgrade issues in the future, install your dependencies with the `--exact` flag, like this: `yarn add --exact react-native-htmlview`.

**Comment by johntom** [comment]
Thanks for that tip and will try tomorrow

**Comment by richchurcher** [comment]
In theory, `react-native-htmlview` should work correctly even if the `prop-types` package is not installed in the parent project (just tried it with a fresh app). I'm not quite sure what issue you're encountering here but I don't _think_ it's related to this package. If you can reproduce it with a fresh `create-react-native-app` and post a repo for us to look at, please do! Closing for now though.
