### ISSUE TITLE
Support styling based on class

### ISSUE THREAD

**Issue by atardadi** [jsdf/react-native-htmlview#13]
Would be highly appreciated :)

**Comment by itinance** [comment]
+1 @atardadi

**Comment by vtisnado** [comment]
+1 @jsdf

**Comment by h4ck4life** [comment]
+1

**Comment by richchurcher** [comment]
It's certainly a possibility, though I think other fixes are probably higher up the priority list. PRs welcome! :smile:

**Comment by aryankothiyal** [comment]
any update on same?

**Comment by arthedza** [comment]
Are any updates on this?
