### ISSUE TITLE
Text direction is randomized ?

### ISSUE THREAD

**Issue by yogevlahyani** [jsdf/react-native-htmlview#141]
Hi, I have a screen that's changes text in htmlview on button click, it seems that the text alignment is changing randomly (I have a forced ltr app, on my rtl device)

**Comment by richchurcher** [comment]
Hi @yogevlahyani :) Can you provide a minimal example that reproduces the problem please? Also say device/version, React Native version and `react-native-htmlview` version.

**Comment by yogevlahyani** [comment]
Hi @richchurcher :)
My device is LG-H815 android 6.0
My device system language is Hebrew so my device has RTL.

`
"react": "^16.0.0-alpha.12",
"react-native": "^0.46.3",
"react-native-htmlview": "^0.9.0",
`

I can't actually give an example right now, but like I explained it is showing me the HTMLView text aligned left or right (it even once centered my text) randomly ..

I will edit a GIF soon, Thank you :)

**Comment by richchurcher** [comment]
It really would be beneficial to see a source example just to make sure we can reproduce what you're seeing... otherwise it's just guesswork! Doesn't have to be complicated at all, just a few lines from an `App.js` in a newly-created `create-react-native-app` is the simplest way I find.
