### ISSUE TITLE
how to set paragraph space 

### ISSUE THREAD

**Issue by Liqiankun** [jsdf/react-native-htmlview#142]
This is my style of p tag 
```
const htmlStyle = StyleSheet.create({
  p: {
    margin: 5
  }
});
```
But It does not work. The paragraph space is still huge！
![simulator screen shot 2017 8 3 6 36 14](https://user-images.githubusercontent.com/11532418/28918109-ae6c3272-787a-11e7-8095-abaa57f852d0.png)

**Comment by Liqiankun** [comment]
After I set `addLineBreaks={false}`the space is still not what I want!

**Comment by richchurcher** [comment]
We currently aren't able to fine-tune paragraph spacing beyond using `paragraphBreak`, `lineBreak`, and `addLineBreaks`. PRs in that area very welcome though :smile:

**Comment by Liqiankun** [comment]
@richchurcher OK, thanks  man!

**Comment by Jayiitb** [comment]
Thanks for this wonderful component.
Any progress on this issue?

**Comment by richchurcher** [comment]
@Jayiitb no, but it's definitely something I'm looking at. I feel like there ought to be a way for us to set `marginTop` sensibly, so I'm investigating that.

**Comment by richchurcher** [comment]
Note that doing something like this comes pretty close:
```
    return (
        <HTMLView
          addLineBreaks={false}
          stylesheet={richTextStyles}
          value={content} />
    )

// ...

const richTextStyles = StyleSheet.create({
  p: {
    marginTop: 3,
    marginBottom: 3
  }
})
```

**Comment by optimatex** [comment]
@richchurcher That works very well in my case. Thanks!

**Comment by eidsza1** [comment]
This work perfect 

`value={"<div>"+ item +"</div>"}`

**Comment by gyawalirajiv** [comment]
Thanks @eidsza1 and @richchurcher . worked
