### ISSUE TITLE
Questions about blocking UI threads

### ISSUE THREAD

**Issue by ifzm** [jsdf/react-native-htmlview#145]
Hello, when i parse a larger html, block the main thread for a long time, what are the optimization options?

**Comment by richchurcher** [comment]
Yeah, that's almost inevitable with larger chunks of markup (which this library isn't very well-suited to dealing with). You could possibly chunk the data you're processing using a series of `HtmlView`s and `requestAnimationFrame` (see https://facebook.github.io/react-native/docs/timers.html) to break up the work.

**Comment by ifzm** [comment]
Yeah，i can only think so.
Thank you for your enthusiastic answer :D
