### ISSUE TITLE
Update NPM Package

### ISSUE THREAD

**Issue by sf577** [jsdf/react-native-htmlview#15]
Hi, 

Can you possibly push the recent changes to NPM? 

Best regards

Steven Fisher

**Comment by jsdf** [comment]
Can you test the version 0.4.0 I just published?

**Comment by sf577** [comment]
I upgraded to 0.4.0 and got the following error
<img width="466" alt="screen shot 2016-04-11 at 16 32 15" src="https://cloud.githubusercontent.com/assets/3382478/14432686/202ea2ba-0003-11e6-805d-7f0a809409b1.png">

**Comment by jsdf** [comment]
Looks like the `.babelrc` file I added for the tests is interfering. I've just published `0.4.1` which adds it to the `.npmignore`. Can you try it out and tell me if it fixes the issue for you?

**Comment by sf577** [comment]
That seems to have fixed it cheers!
