### ISSUE TITLE
<p> and <img> tag combine not working

### ISSUE THREAD

**Issue by JaekwanJeon** [jsdf/react-native-htmlview#150]
Hello~!

 `<p><img src ...></p>` image not displayed
but `<img src ...>` image displayed.

(1) it's not work(img not displayed)

```
                <HTMLView
                  value='<p><br></p><p><img src="https://assets-cdn.github.com/images/modules/site/integrators/slackhq.png" class="txc-image" style="clear:none;float:none;"></p>'
                />
```

(2) it's work(img displayed)
(
 ```
              <HTMLView
                  value='<p><br></p><img src="https://assets-cdn.github.com/images/modules/site/integrators/slackhq.png" class="txc-image" style="clear:none;float:none;">'
                />
```

how can display image with `<p>` tag?

**Comment by mrcaobin** [comment]
I got same problem

**Comment by ciriac** [comment]
Is this on Android? This is because nesting of views is [not supported on Android](http://facebook.github.io/react-native/releases/0.42/docs/text.html#nested-views-ios-only).

Does anyone have a fix or workaround for this?

**Comment by richchurcher** [comment]
@JaekwanJeon It works, you just have to add a width and height:
```
    const htmlContent = `<p><img height="200" width="200" src="https://assets-cdn.github.com/images/modules/site/integrators/slackhq.png"></p>`
```

@ciriac I don't think that problem is related, since inserting an image nests an `<Image />` not a `<View>`.
