### ISSUE TITLE
Inline Image

### ISSUE THREAD

**Issue by korgara** [jsdf/react-native-htmlview#151]
Hi. Thank for this great lib, but there is a kind a wierd trouble.
I tried to parse emoji images ``` <img class="emoji" width="40" height="40" src='http://192.168.0.107:1911/static/emoji/${index}.png' />``` and it works, but all images behave themselves as a 'display: block'.
![2017-09-06 12-29-14](https://user-images.githubusercontent.com/24753645/30104741-339f1ace-92ff-11e7-8be3-d1482717c56a.png)

I tried to change a RootComponent to Text, but emojis isnt vertical align themselves relatively text

![123](https://user-images.githubusercontent.com/24753645/30104939-c3a9c948-92ff-11e7-8286-9d074480c272.png)

How can I make it as 'display: inline-block' without breaking the vertical align rules ?

**Comment by richchurcher** [comment]
Yeah, it's tricky... this definitely isn't a complete re-implementation of CSS (for good reason). One thing that might help you a little is to ensure your image is inside a wrapping `<div>`:
```
    const htmlContent = `<div><img src='http://d2trtkcohkrm90.cloudfront.net/images/emoji/apple/ios-10/256/dizzy-face.png' /> wow</div>`
```

**Comment by richchurcher** [comment]
Yeah, it's not ideal. This is far from a complete re-implementation of CSS (the component deliberately tries to keep things fairly simple). One thing you can try is to wrap your content in a `<div>`:
```
    const htmlContent = `<p><img width="80" height="80" src='http://d2trtkcohkrm90.cloudfront.net/images/emoji/apple/ios-10/256/dizzy-face.png' /> wow</p>`
```

**Comment by angleneo** [comment]
How to solve this problem ？
