### ISSUE TITLE
Replace View.propTypes with ViewPropTypes

### ISSUE THREAD

**Issue by JohnBlazek** [jsdf/react-native-htmlview#152]
Receiving this warning when using this module. 

```Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.```

Currently building with "react-native": "0.46.4"

**Comment by richchurcher** [comment]
This was already addressed in #140... you might need to update your version.

**Comment by richchurcher** [comment]
Sorry, yeah it hasn't made it across yet. I can't publish to npm, was going to wait until we had a bit more but maybe @jsdf can patch release if it's causing issues.

**Comment by lukebaker** [comment]
We were seeing immediate crashes of our release build of our app after upgrading to React Native 0.49 and using react-native-htmlview 0.12.0.

**Comment by richchurcher** [comment]
If you need an interim solution use the commit hash in your `package.json`... otherwise it'll be whenever the project owner has a free moment :smile:

**Comment by lukebaker** [comment]
> If you need an interim solution use the commit hash in your package.json

Yep, that's what we ended up going with for now. Thanks!
