### ISSUE TITLE
How can i use the native copy and paste ,like Text Component selectable?

### ISSUE THREAD

**Issue by laclys** [jsdf/react-native-htmlview#153]
How can i  use the native copy and paste ,like Text Component selectable

**Comment by laclys** [comment]
help!!!!!!!

**Comment by rneiss** [comment]
Use `nodeComponentProps={{selectable: true}}`

**Comment by lucaszanella** [comment]
Didn't work for me. Did something change?

**Comment by lucaszanella** [comment]
`textComponentProps={{selectable: true}}`
did the trick for me

**Comment by noway** [comment]
Any way to select by words like here? https://github.com/facebook/react-native/issues/13938#issuecomment-520590673

**Comment by bakoserge** [comment]
> Any way to select by words like here? [facebook/react-native#13938 (comment)](https://github.com/facebook/react-native/issues/13938#issuecomment-520590673)

Any solutions for this question?

**Comment by nes123** [comment]
+1
