### ISSUE TITLE
Too large space between html elements

### ISSUE THREAD

**Issue by ibogdan94** [jsdf/react-native-htmlview#159]
First of all, thank you for package :)

My react components, which was parsed by this package have a very big space and I don't know how I can fixed it

My code looks like:

        let result = [];

        htmlDataArray.forEach(value=> {
          result.push(<HTMLView stylesheet={htmlTCStyles} value={value.textApi}/>);
        });

        return (
          <View>
            {result.map(element => {
               return element
            })}
          </View>);

And as a result I have:

![screenshot 2017-10-02 19 52 05](https://user-images.githubusercontent.com/11140851/31088986-39105e12-a7ab-11e7-947e-2aae8cd338ed.png)

How I can fixed this issue?

**Comment by jeiemgi** [comment]
I have the same issue, someone knows?

**Comment by ibogdan94** [comment]
@jeiemgi usual html. Nothing special

`<p><strong>We provide hands-on</strong> legal guidance on Internet and technology issues such as: online business disputes; general cyberlaw consulting; trademarks and trademark/service mark disputes; cybersquatting and typosquatting; domain name disputes; copyrights and copyright disputes; the Digital Millennium Copyright Act (DMCA); Internet torts and privacy; the Communications Decency Act (CDA &sect;230); <em>defamation and</em> <s>First Amendment issues;</s> advertising networks and affiliate marketing; Internet startups; licensing, contracts, website terms of use, privacy policies and EULAs; bitcoin and cryptocurrencies; and other varied issues arising in a still rapidly changing technological landscape.</p>
<p>Test</p>
<h2>Headinf:</h2>
<ol>
<li><var>Test</var></li>
<li><strong>Trololo</strong></li>
<li><ins>fsdfsdf</ins></li>
<li><strong>sdfsdfsdf</strong></li>
</ol>
<p><strong>List:</strong></p>
<ul>`

**Comment by optimatex** [comment]
Hi @ibogdan94  
How did u solve this?

**Comment by bispul** [comment]
I think it needs to be reopened because i don't think anyone have mentioned how to solve this issue. This is misleading. 
Really, how did you solve this issue?

**Comment by jeiemgi** [comment]
@bispul Hi, in my personal case, I had to be aware of blank spaces, and line breaks because the library takes that as a real blank space left on purpose.

**Comment by nikasvan** [comment]
any fix for this? I tried `addLineBreaks={false}` but there are still some spaces left

**Comment by richchurcher** [comment]
@bispul @nikasvan please refer to https://github.com/jsdf/react-native-htmlview/issues/142#issuecomment-331679944 and open another issue with a specific problem if this doesn't help :smile:

**Comment by brechtwaeghe** [comment]
@richchurcher @nikasvan I had the same problem with data coming from a rich text editor. I solved it by removing the hidden \r line breaks.

**Comment by Delwalt** [comment]
I used the negative margin to solve the issue, it worked! though I don't know if it is a good idea or not. 

`const htmlViewStyle= StyleSheet.create({
  p: {
    marginBottom: -80
  }
})
`

**Comment by inferusvv** [comment]
Has anyone fixed that? I just render WordPress HTML content and have that large spacing.

**Comment by inferusvv** [comment]
Ok, I wrote function which will remove white space between tags. Just workaround.

`export const clearContentWhitespace = data => replace(/(<\/.+>)(\s+)(<)/g, '$1$3', data);`

**Comment by trd-peraltajim** [comment]
this will do the trick:

<HTMLView value={`<mytag>${data.replace(/(\r\n|\n|\r)/gm, "")}</mytag>`} renderNode={renderNode}/>
