### ISSUE TITLE
style: View.propTypes.style

### ISSUE THREAD

**Issue by PatrikTes** [jsdf/react-native-htmlview#161]
Hello, even that on git is the version with style: ViewPropTypes.style, when I get the version over npm I receive the old one.

What I'm doing wrong? Version 0.12.0
P.S. I'm using React 16

**Comment by DomiR** [comment]
It is already fixed in 9e3dfec70b536061c23279d464c506fc973a7cb0, but not published on npm. Pretty please 🐹
