### ISSUE TITLE
iframe youtube video doesn't work in android device at all.

### ISSUE THREAD

**Issue by kagmanoj25** [jsdf/react-native-htmlview#165]
iframe youtube video doesn't work in android device, an iOS device the view will appear but an initial image of a video doesn't show, also iframe image too doesn't show properly in android device.
I really appreciate for your valuable reply.

**Comment by isilher** [comment]
Hello @kagmanoj25. This library is meant to support basic translation of html elements, not to offer a full browser-experience. iframe components are not supported by default, but there is an example of how to implement them yourself [in the README](https://github.com/jsdf/react-native-htmlview#custom-element-rendering). If you follow that approach, the possibilities will only be limited by the [WebView](https://facebook.github.io/react-native/docs/webview.html).

**Comment by kagmanoj25** [comment]
@isilher Yes iframe components are not supported by default. I also followed the example from [REAMDME](https://github.com/jsdf/react-native-htmlview#custom-element-rendering). But it only works with the iOS which is really good, whenever I tried with the Android device the renderNode function doesn't call and I don't know why? I hope you will understand my problem.

**Comment by isilher** [comment]
@kagmanoj25 I've just tested on a Moto G (Android 6.0.1) and the iframe shows as expected. Note that you do have to make sure the wrapping `<div>` elements in the example are rendered as elements other than `<Text>` (Android will crash when you attempt to display non-Text children within Text components)

If that does not solve your problem, please add an example of your implementation.

**Comment by kagmanoj25** [comment]
@isilher thanks for your feedback and sorry to say that this library is meant to support the basic translation of HTML elements, which is perfectly working with iOS but not with Android. I found the alternate way to solve this issue.

**Comment by atillasertkaya** [comment]
@kagmanoj25 How did you solve the issue? I faced the same issue in my project

**Comment by NySiya** [comment]
Why this issue is closed, while there is no solution :( ?

**Comment by atillasertkaya** [comment]
@NySiya There is no solution, then I had to change the plugin. The following plugin is working well. 

https://github.com/archriss/react-native-render-html

**Comment by NySiya** [comment]
@atillasertkaya  and @isilher, thank you so much for your response.

**Comment by tahirawan4** [comment]
Please write custom renderer for iframe, works great for me.

     function renderNode(node, index, siblings, parent, defaultRenderer) {
       if (node.name == 'iframe') {
              const a = node.attribs;
    const iframeHtml = `<iframe src="${a.src}"></iframe>`;
    return (
      <View key={index} style={{width: Number(a.width), height: Number(a.height)}}>
        <WebView source={{html: iframeHtml}} />
      </View>
    );}}



     const htmlContent = '
      <div>
       <iframe src="http://info.cern.ch/" width="360" height="300" />
      </div>
    ';

     class App extends React.Component {
       render() {
       return (
       <HTMLView value={htmlContent} renderNode={renderNode} />
        );}}
