### ISSUE TITLE
How to set text color or parse html color?

### ISSUE THREAD

**Issue by nguyenhoanglam** [jsdf/react-native-htmlview#169]
I've this HTML
```
<font color=\'red\'>ABCDEF...XYZ</font>'
```

HtmlView does not show text in RED. Is there a way to set HTML text color?

**Comment by richchurcher** [comment]
`<font>` is obsolete in HTML5 (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font). Regardless, react-native-htmlview doesn't read the `color` attribute from tags, so I'm afraid you will need to style using the stylesheet prop (see the docs).
