### ISSUE TITLE
Invariant Violation: Nesting of <View> within <Text> is not supported on Android

### ISSUE THREAD

**Issue by TornHub** [jsdf/react-native-htmlview#170]
Hi, I'm trying to use the Text tag inside the View tag but getting the error below. How can I fix this?

![ekran alintisi](https://user-images.githubusercontent.com/25257157/32148875-8e19389e-bd0d-11e7-9d03-e0c8dc371860.PNG)

**Comment by machour** [comment]
Hi @TornHub, you may want to give a sample HTML code that reproduce your problem in order to get some help :)

**Comment by omegatiger** [comment]
Hi Machour,

This example https://github.com/jsdf/react-native-htmlview/blob/master/example/Example.js **in Android**.

**Comment by omegatiger** [comment]
https://github.com/jsdf/react-native-htmlview/issues/111
