### ISSUE TITLE
Custom fontFamily not supported on Android ?

### ISSUE THREAD

**Issue by thiname** [jsdf/react-native-htmlview#174]
We try to set a custom fontFamily for a react-native-htmlview. It works well with iOS and in Android it also work with the basic <text> component but not in an HTMLview.

We set it this way :
const contentStyles = StyleSheet.create({
  h1: {
    fontSize: 40,
    fontFamily: 'BodoniSvtyTwoITCTT-Bold',
    color: '#79AB2B',
    fontWeight: '700'
  },
  p: { fontSize: 18 }
})
How can we solve this problem ?
Thanks a lot.

**Comment by thiname** [comment]
The problem was related to the fontWeight. The fontWeight 700 was not available in this font and so Android load another font.

**Comment by richchurcher** [comment]
Yep, Android will fall back to a default anytime it doesn't find the correct weight. Been bitten by that a few times :smile:
