### ISSUE TITLE
Many issue found with Android support in react-native-html

### ISSUE THREAD

**Issue by kagmanoj25** [jsdf/react-native-htmlview#177]
There are many issues found with Android support. Still, I'm not getting any reply to my question [#165](https://github.com/jsdf/react-native-htmlview/issues/165). In Android iframe has not been supported at all so I can't play youtube video even not able to displaying image too. I really appreciate if I will get any positive reply whether it is possible or not.

**Comment by isilher** [comment]
@kagmanoj25 I understand not getting an answer can be frustrating, but demanding attention by creating multiple issues is not very nice or helpful. I took the time to answer your original question this time, but expect people will be more likely to ignore you if you behave like that.

**Comment by kagmanoj25** [comment]
@isilher Thank you @isilher for attention to my question. you are right, I'm frustrated a little bit. From now I will not repeat this mistake.
