### ISSUE TITLE
How does the table tr td tag change and how do you set their width and height on the front end if the image returned in the background

### ISSUE THREAD

**Issue by gaozhaopei** [jsdf/react-native-htmlview#179]

**Comment by gaozhaopei** [comment]
后台返回的图片高度和宽度如何设置

**Comment by richchurcher** [comment]
Hi @gaozhaopei . I'm closing this one due to inactivity and, well, not really understanding the question :smile: If you're still having trouble, feel free to post but please provide a bit more detail and some code.

**Comment by gaozhaopei** [comment]
有办法将sup sub 这种标签进行转化吗

**Comment by gaozhaopei** [comment]
@richchurcher

**Comment by isilher** [comment]
@gaozhaopei we don't understand your question, could you attach an example of the HTML you're trying to display and describe the expected outcome?
