### ISSUE TITLE
Inline images are not subject of styling in the app on Android

### ISSUE THREAD

**Issue by Taimoormk** [jsdf/react-native-htmlview#187]
![screenshot_1512191544](https://user-images.githubusercontent.com/27800340/33816352-09f13f76-de5a-11e7-83e2-4a6e1693e600.png)
![simulator screen shot - iphone 6 - 2017-12-02 at 10 12 21](https://user-images.githubusercontent.com/27800340/33816415-870b1176-de5a-11e7-82fb-873388ca2b6a.png)

Attached are screenshots of iOS and Android platform using RN script. As you can see, the inline images are rendering out on iOS as desired but on Android platform it appears that styling are not having any affect on the inline images, please could you suggest how to fix this as I am using RN HTMLView dependency to render it out.

**Comment by richchurcher** [comment]
Hi. It's really difficult to tell without seeing some code. Can you either post some code from your project, or (even better) create a minimal example that reproduces the problem? You could use this template if it helps:

```js
import React from 'react';
import HTMLView from 'react-native-htmlview'
import { StyleSheet, View } from 'react-native';

export default class App extends React.Component {
  render() {
    const htmlContent = `<p>This paragraph has an <em>emphasised</em> word.</p>`
    const stylesheet = StyleSheet.create({
      p: {
        paddingLeft: 20,
        paddingRight: 20,
        textAlign: 'center'
      }
    })
    const styles = StyleSheet.create({
      container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center'
      },
      defaultStyle: {
        color: '#231F20',
        fontSize: 14,
        lineHeight: 18
      }
    })
    return (
      <View style={styles.container}>
        <HTMLView
          stylesheet={stylesheet}
          textComponentProps={{ style: styles.defaultStyle }}
          value={htmlContent} />
      </View>
    )
  }
}
```
