### ISSUE TITLE
Add isilher as collaborator

### ISSUE THREAD

**Issue by richchurcher** [jsdf/react-native-htmlview#192]
Hi @jsdf ! If he has the inclination, I'd like to explore adding @isilher as a collaborator to the project. He has been extremely helpful in issues and contributions, and I usually find more collaborators helps things run smoother :smile:

**Comment by jsdf** [comment]
Sounds good to me, @isilher are you interested in being added as a collaborator?

**Comment by isilher** [comment]
Hi @richchurcher, @jsdf! Thanks for the invitation. Before I jump in (I'm happy to help), what would be expected of me?

**Comment by richchurcher** [comment]
Well doing what you're doing now, except maybe reviewing/accepting/declining PRs as well? Just making sure CI builds are passing etc. Every now and again when I've collected enough changes I ask James to publish to npm and I make sure the docs & changelog reflect the changes. That's about it :smile:

**Comment by isilher** [comment]
Yeah, I'd be happy to. :)

**Comment by jsdf** [comment]
Done! Welcome @isilher, and thanks for helping out!

**Comment by isilher** [comment]
Thanks! 🎉
