### ISSUE TITLE
If change fontSize of root (body) tag, the <HTMLView> is not rendering the html text 

### ISSUE THREAD

**Issue by duyhung16** [jsdf/react-native-htmlview#198]
In my case, when change fontSize of the body tag from 20 -> 21 ( or any value > 20 ), <HTMLView> is not rendered.

${htmlContent} length: 26848

```
const htmlViewStyles = StyleSheet.create({
      body: {
        flex: 1,
        fontSize: 20, // -> can not change o 21
        paddingHorizontal: 10,
        paddingTop: 40,
        textAlign: 'justify'
      }
    })
```

```
<ScrollView style={styles.container}>
    <HTMLView value={`<body>${htmlContent}</body>`}  stylesheet={htmlViewStyles}/>
</ScrollView>
```

**Comment by isilher** [comment]
@duyhungp does the same happen with a shorter html content? This might be related to: https://stackoverflow.com/questions/41001693/large-amount-of-text-not-rendering-properly-in-a-scroll-view-react-native

(See also #189)

**Comment by duyhungp** [comment]
@isilher a shorter html content does not happen. 
May be need separate large <Text> component into several smaller <Text> components. i'll try

**Comment by gdxie1** [comment]
I added a key={} and evey time when I want to re-render, I just change the key value.
