### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by cgarvis** [jsdf/react-native-htmlview#2]

**Comment by smpetrey** [comment]
+1 that would be rad

**Comment by sjoonk** [comment]
+1 I hope so.

**Comment by chshouyu** [comment]
+1024

**Comment by Kuchitama** [comment]
+1

**Comment by jsdf** [comment]
I'd happily accept a PR. This wouldn't be particularly difficult to implement, I just don't have time to do it any time soon.

**Comment by kxxoling** [comment]
Really need this feature, but I don't know how to implement it. Poor knowledge with JS and iOS. :(

@jsdf If you have any idea but no time, how about writing it down and wait someone to implement it?

**Comment by ufon** [comment]
+1

**Comment by ufon** [comment]
I trying somsing but it not work :(


```
if (node.type == 'tag') {
        var linkPressHandler = null
        if (node.name == 'a' && node.attribs && node.attribs.href) {
          linkPressHandler = () => opts.linkHandler(entities.decodeHTML(node.attribs.href))
        }
        if (node.name == 'img' && node.attribs && node.attribs.src) {
          linkPressHandler = () => node.attribs.src
        }
        return (
          <Text key={index} onPress={linkPressHandler}>
            {node.name == 'pre' ? LINE_BREAK : null}
            {node.name == 'li' ? BULLET : null}
            {node.name == 'li' ? <Image style={height: 300} source={{uri: linkPressHandler}} /> : null}
            {domToElement(node.children, node)}
            {node.name == 'br' || node.name == 'li' ? LINE_BREAK : null}
            {node.name == 'p' && index < list.length-1 ? PARAGRAPH_BREAK : null}
            {node.name == 'h1' || node.name == 'h2' || node.name == 'h3' || node.name == 'h4' || node.name == 'h5' ? PARAGRAPH_BREAK : null}
          </Text>

          
          )
      
      }
```

**Comment by cinic2003** [comment]
+1 hope it very much

**Comment by kxxoling** [comment]
I'm using `react-native-html-render` instead, but its document is bad, you can take my app as an example: https://github.com/kxxoling/PythonChina.app/blob/master/views%2FPost.js

**Comment by blankzust** [comment]
+1.

**Comment by ufon** [comment]
@kxxoling i found this week ago. work's perfectly

**Comment by kxxoling** [comment]
@ufon Except some compatibility with HTML5 tags. For example, if you put a ``img`` tag in an ``figure`` tag, the image won't show. I've created an issue about this, but not fixed yet.

**Comment by ufon** [comment]
@kxxoling it's not so critical, I am sure this is remediable at a stage of response preparation :)

**Comment by kxxoling** [comment]
@ufon Yeah, but I'm working on an app based on python-china.org's API, which prefer HTML5 tags.

**Comment by blackbing** [comment]
@jsdf I've send a pull request https://github.com/jsdf/react-native-htmlview/pull/18. Please help to review it.

**Comment by ladjzero** [comment]
I'll try @blackbing 's approach.

**Comment by blackbing** [comment]
if you want to point to my version temporary before this issue resolved. 
Try this
`npm i git+https://git@github.com/blackbing/react-native-htmlview.git#master`

**Comment by JO-WTF** [comment]
@kxxoling 

Thanks a lot.

Maybe I will help in improving the documents.

**Comment by JO-WTF** [comment]
@jsdf 
Could you please merge @blackbing 's PR?

Thanks.

**Comment by melihmucuk** [comment]
@blackbing it doesn't work on React Native v0.30.

**Comment by vincentschen** [comment]
+3 @liezl200 @allisonsun
