### ISSUE TITLE
Get parsed html

### ISSUE THREAD

**Issue by judemanutd** [jsdf/react-native-htmlview#212]
Is there a way to get the html that is parsed by the library ?

**Comment by isilher** [comment]
@judemanutd can you give an example of what you mean with "the html that is parsed"? The library takes an HTML string that you provide, and returns a React Native nested component structure.

**Comment by judemanutd** [comment]
Assuming I have html content like so " Random &amp Text" which when parsed displays as "Random & Text" which is displayed perfectly by the component. Is there a way that I can get this parsed text "Random & Text" for processing later on.

**Comment by isilher** [comment]
@judemanutd I think the library you're looking for is https://github.com/fb55/entities.

**Comment by judemanutd** [comment]
That actually worked, thank you.
