### ISSUE TITLE
Empty area where defined a custom renderNode

### ISSUE THREAD

**Issue by donni106** [jsdf/react-native-htmlview#219]
I have a custom `renderNode` for `<ul>` and `<li>` and it is working fine when running on a simulator.
If I build a release version on a real device, the same `<ul>` and `<li>` were not visible. I tried to figure out the bad lines, but nothing helped.

Somebody ever experienced the same?

Tested on iOS with ReactNative: 0.55.4

**Comment by juancabraal** [comment]
I'm having the same problem here, I have tried to change the lineheight as was suggested but still dont working

**Comment by rochapablo** [comment]
Any update on this?

**Comment by donni106** [comment]
Don't know, I am using this now since a while: https://github.com/archriss/react-native-render-html

**Comment by club9822** [comment]
Try to set `margin:0 padding:0 `for that custome node renderer

**Comment by club9822** [comment]
> Don't know, I am using this now since a while: https://github.com/archriss/react-native-render-html
This module uses  `WebView`.

**Comment by donni106** [comment]
And you don't want to use that because of the WebView implementation @club9822?

**Comment by club9822** [comment]
> And you don't want to use that because of the WebView implementation @club9822?

yes
