### ISSUE TITLE
Cut a release for v0.13.0

### ISSUE THREAD

**Issue by jsdf** [jsdf/react-native-htmlview#229]
- [x] master is passing tests
- [x] manual testing
  - [x] create a new react native app which renders [Example.js](https://github.com/jsdf/react-native-htmlview/blob/master/example/Example.js) and test that it works
- [ ] bump version number
- [x] update release notes with merged PRs since 0.12.1

**Comment by alphasp** [comment]
@jsdf Can you have a look at this PR #228 before new release?

**Comment by jsdf** [comment]
https://github.com/jsdf/react-native-htmlview/releases/tag/v0.13.0
