### ISSUE TITLE
error because of the require

### ISSUE THREAD

**Issue by petersg83** [jsdf/react-native-htmlview#26]
At the line of my _require('react-native-html-webview');_ (DumbProduct.js:10:0) it throws the error **"undefined is not an object (evaluating 'PropTypes.string")**. 
![screenshot_20160607-161453](https://cloud.githubusercontent.com/assets/11708220/15860899/2990f1a6-2ccb-11e6-99b3-cc7f7af0f232.png)

Funny fact : my index.ios.js file is only 6 lignes long.

**Comment by olup** [comment]
Here too, with android

**Comment by nasal** [comment]
It looks like you are trying to require `react-native-html-webview` instead of `react-native-htmlview`.

Try with `var HTMLView = require('react-native-htmlview')`.
