### ISSUE TITLE
componentWillReceiveProps is deprecated

### ISSUE THREAD

**Issue by Auticcat** [jsdf/react-native-htmlview#262]
Hello,

as i couldn't find an issue pointing it out. Using react-native 0.60+ there's this warning popping out while using this component about componentWillReceiveProps being deprecated.

As a workaround for now i'm using `YellowBox.ignoreWarnings(['componentWillReceiveProps']);`

The full warning says: 
`Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.`

Thank you in advance!

**Comment by Auticcat** [comment]
For now i changed:
`  componentWillReceiveProps(nextProps) {
    if (this.props.value !== nextProps.value || this.props.stylesheet !== nextProps.stylesheet || this.props.textComponentProps !== nextProps.textComponentProps || this.props.nodeComponentProps !== nextProps.nodeComponentProps) {
      this.startHtmlRender(nextProps.value, nextProps.stylesheet, nextProps.textComponentProps, nextProps.nodeComponentProps);
    }
  }`

to 

` componentDidUpdate(prevProps) {
    if (this.props.value !== prevProps.value || this.props.stylesheet !== prevProps.stylesheet || this.props.textComponentProps !== prevProps.textComponentProps || this.props.nodeComponentProps !== prevProps.nodeComponentProps) {
      this.startHtmlRender(this.props.value, this.props.stylesheet, this.props.textComponentProps, this.props.nodeComponentProps);
    }
  }`

inside /react-native-htmlview/HTMLView.js at line 57 to

` componentDidUpdate(prevProps) {
    if (this.props.value !== prevProps.value || this.props.stylesheet !== prevProps.stylesheet || this.props.textComponentProps !== prevProps.textComponentProps || this.props.nodeComponentProps !== prevProps.nodeComponentProps) {
      this.startHtmlRender(this.props.value, this.props.stylesheet, this.props.textComponentProps, this.props.nodeComponentProps);
    }
  }`

and seems to work fine.

**Comment by LuigiMaestrelli** [comment]
Also getting this warnings.
Any idea about when a fix will be released?

**Comment by jsdf** [comment]
fixed by https://github.com/jsdf/react-native-htmlview/pull/263
published https://github.com/jsdf/react-native-htmlview/tree/v0.15.0
