### ISSUE TITLE
ITMS-90809: Deprecated API Usage - UIWebView

### ISSUE THREAD

**Issue by WestFR** [jsdf/react-native-htmlview#270]
We identified one or more issues with a recent delivery for your app, "APP_NAME". Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

--

Many applications can be used this package for production environments in AppStore or GooglePlay. Please, consider this issue and update this amazing librairie.

Because, after few app update by worldwide developer, Apple stop app submission who don't respect this new rules. Thanks for all ! And thanks for this package work ! 

So, we need to switch from UIWebView (UIKit) to WKWebView (WebKit) : https://developer.apple.com/documentation/webkit/wkwebview

**Comment by BogdanTaranenko** [comment]
why this issue is closed?

**Comment by appinteractive** [comment]
Hey I do have the same issue now. Is it caused by that library or is this a react native version thing? After searching here for UIWebView I did not found any mention in this repo through the GitHub search at least.
