### ISSUE TITLE
are we using UIWebView?

### ISSUE THREAD

**Issue by girish54321** [jsdf/react-native-htmlview#288]
is this package using UIWebView
i got mail form apple
Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from April 2020

Environment:
OS: Mac OS
OS version:
react-native version:0.59.10
react-native-webview version: 7.5.2
react-native-htmlview : 0.12.2 // 0.15.0

**Comment by Doliant** [comment]
I have the same question.

**Comment by philippbosch** [comment]
I'm pretty sure UIWebView is *not* used anywhere. The HTML content is parsed and each node is mapped to a RN view. That's it.

**Comment by girish54321** [comment]
thanks @philippbosch
