### ISSUE TITLE
Table tag support?

### ISSUE THREAD

**Issue by radiegtya** [jsdf/react-native-htmlview#29]
table tag is not detected

**Comment by IronTony** [comment]
Any news about this?

**Comment by jaseemabbas** [comment]
+1

**Comment by koenpunt** [comment]
You can implement this yourself by passing a function to `renderNode`. Although I think I might be a lot of work...

**Comment by richchurcher** [comment]
`<table>` isn't likely to be supported in the near future... PR welcome though! :wink:

**Comment by Reier360** [comment]
@richchurcher Hi, so this does not yet support table?

**Comment by MayeuldP** [comment]
Pop ? still waiting for <table>.... Any alternative to it ?

**Comment by isilher** [comment]
@MayeuldP This has not been implemented and is not likely to be supported in the near future. You're welcome to submit a PR with a solution.

**Comment by MayeuldP** [comment]
@isilher at least could you manage/skipping it well ? Because if I got a `<table>`, the html content crashed, and it doesnt works well, even with using a `renderNode` function and skip `<table>` attribut, still get some troubles :/

**Comment by jsamr** [comment]
Table support requires grid layout ; you cannot support advanced table features such as `rowspan` and `colspan` without it. Grid layout is not yet supported by React Native, but [**you can upvote it here**](https://react-native.canny.io/feature-requests/p/css-grid-layout-supporting).
