### ISSUE TITLE
Lineheight in Android

### ISSUE THREAD

**Issue by GCour** [jsdf/react-native-htmlview#30]
Regarding this Stackoverflow question:
http://stackoverflow.com/questions/38076639/lineheight-in-htmlview

I'm not able to set a line-height in Android. It works fine for iOS

**Comment by GCour** [comment]
Sommerfeld, I don't get it.. I want my description to have a lineHeight. How can I do this?

  <HTMLView
        value={itemDetail.description}
        stylesheet={{p:{lineHeight:32}}}/>

**Comment by richchurcher** [comment]
@GCour this is working on Android in the current version. If you continue to have any difficulties, can you open a new issue? Thanks!
