### ISSUE TITLE
How to get onPress work?

### ISSUE THREAD

**Issue by winglight** [jsdf/react-native-htmlview#40]
I hope to handle the event when user click any place on the htmlview, code's followed:
`
<ScrollView
          style={{flex: 1}}>
          <HTMLView style={{flex: 1}}
            value={this.state.content}
            onPress={() => this._toggleToolbar()}
          />
          </ScrollView>
`

**Comment by nasal** [comment]
Wrap it into a `<Touchable*>` component.

**Comment by nobalmohan** [comment]
Wrap it in **TouchableOpacity** or **TouchableHighlight**. Learn the difference before using !
