### ISSUE TITLE
Is there a reason for bundling htmlparser2 and entities with this library?

### ISSUE THREAD

**Issue by kengorab** [jsdf/react-native-htmlview#51]
My first assumption was that it was because the bundled dependencies are actually forks of the libraries. While I hope that's not the case, I wasn't able to see any difference between the two (although I could have missed it).

Unless there's a reason not to, I think this library should use [htmlparser2-without-node-native](https://www.npmjs.com/package/htmlparser2-without-node-native) and the normal [entities](https://www.npmjs.com/package/entities) libs.

If there's no issue with this, I can put up a pull request.

**Comment by jsdf** [comment]
The only reason is historical. When I originally created this project, React Native didn't support .json requires and bundling was a way to get around that. I'd happily accept a pull request to remove it.
