### ISSUE TITLE
img tag not support for react-native 0.34?

### ISSUE THREAD

**Issue by SamleLin** [jsdf/react-native-htmlview#57]
img tag not support for react-native 0.34

**Comment by XHTeng** [comment]
had solve this issues ?

**Comment by nobalmohan** [comment]
React native support **Image** tag.
```
          <Image
            style={{width: 150, height: 150}}
            source={{uri: imgUrl}}
          />
```

**Comment by susan-github** [comment]
Any update about supporting <img> tag?
react-native version: 0.38

**Comment by anishtr4** [comment]
does  it support <img   src="https://dz2cdn2.dzone.com/thumbnai.jpg" width="60"> tag ?

**Comment by vedovato** [comment]
i think it's not supported, yet

**Comment by MichelDiz** [comment]
no modules are supporting img tags... I'm trying hard and no success

**Comment by vedovato** [comment]
Can you tell us reasons it is hard, @MichelDiz?

**Comment by jsdf** [comment]
This package supports img tag but the width and height attributes must be set.

**Comment by MichelDiz** [comment]
Okay, but where? inside my Json.description has width="203" height="214" inside the HTML

**Comment by jsdf** [comment]
In the version which I just released, this works:

```html
    <img src="https://i.redd.it/1l01wjsv22my.jpg" width="400" height="400" />
```

**Comment by MichelDiz** [comment]
I gonna try!

**Comment by liezl200** [comment]
With width and height set, img tag rendering works for Android but image is not rendering on iOS (there is a blank space where the image should be).

**Comment by CabuxaMapache** [comment]
Not working for me with "onRenderNode": #94

**Comment by vedovato** [comment]
How are you setting the image dimensions on dynamic content, @liezl200?

**Comment by nicqchen01** [comment]
if we add img with relative path, could add one base URL ? then we could check if it is from web. if not. use base URL to load images.
