### ISSUE TITLE
Style text not contained in tag

### ISSUE THREAD

**Issue by spenceropope** [jsdf/react-native-htmlview#6]
Is there a way to style text not contained in a tag? For instance, in the ReactNativeHackerNews example the beginning of the {comment.text} content is often not included in a tag. Is there a way to apply a style to all of the html content?

**Comment by jsdf** [comment]
How about wrapping it in a root tag before parsing it?

**Comment by spenceropope** [comment]
Perfect. Great idea! Thanks.
