### ISSUE TITLE
你们就不能说个中文吗

### ISSUE THREAD

**Issue by zongxiaomi** [jsdf/react-native-htmlview#61]
😌 醉了 找到了三个控件都是ios 的

**Comment by XHTeng** [comment]
hehe

**Comment by aqnaruto** [comment]
作者是国外的，你就不要提这么垃圾的言论出来丢人了。

**Comment by aqnaruto** [comment]
@zongxiaomi

**Comment by zongxiaomi** [comment]
谁告诉你的都是国外的。那你意思英文的项目就不能讲中文了吗 ？ 为什么有的git 项目是双语的？ 我这也样问也是lj言论，那你说的我的这句能证明你就是个LJ吗 ？ 骂你还脏嘴 @aqnaruto

**Comment by tomi-li** [comment]
@zongxiaomi 
没说不可以用中文，但是国际惯例来说，都是用英文来提问和回答，不管你是哪国人。
提 Issue 请简要的提出你的问题 比如 你遇到了什么问题， 代码是不是有问题等情况。 如果你需要中文文档 可以 fork 然后提出 merge request 给 author。
这么写表情符号，和 题目 和详情无关的 issue 是很不尊重 作者的。
如果你写了一个项目， 别人用你看不懂的语言写一些评论你会怎么想。

**Comment by aqnaruto** [comment]
你脑子被你妈吃了？@zongxiaomi  这个作者不是外国人，狗智商

**Comment by richchurcher** [comment]
I can't read this issue! Is it ready to be closed yet? :smile:

**Comment by aqnaruto** [comment]
it is ought to close ,because the asker is a idiot

**Comment by richchurcher** [comment]
I'll take your word for it!
