### ISSUE TITLE
Is there a way to authorize only some tags (<b /><br /> etc.)

### ISSUE THREAD

**Issue by Ouadie** [jsdf/react-native-htmlview#63]
I want to use htmlView but only accept some basic tags like `<b /> <br /> <strong />` and not `<a /> <img />` etc. is it possible ?

**Comment by nobalmohan** [comment]
Parse the HTML string before passing to htmlView

**Comment by scazzy** [comment]
use the given prop method `renderNode` to block, accept or extend the tags.

Example:
```
renderNode={(node) => {
  if(node.name === 'audio') {
    return false;
  }
  if(node.name === 'iframe') {
    const iframeHtml = "<iframe"+ {...node.attribs} +"></iframe>";
    return <WebView key={'node_iframe'} source={{html: iframeHtml}} style={{width: 200, height: 200}} />
  }

}}
```

**Comment by nandastone** [comment]
The result of `renderNode` should be *null*, not *false*: https://github.com/jsdf/react-native-htmlview/blob/master/htmlToElement.js#L39

Returning false will simply fallback to the default node renderer.

```
if(node.name === 'audio') {
  return null;
}
```
