### ISSUE TITLE
Latest version not released to npm 

### ISSUE THREAD

**Issue by ismdcf** [jsdf/react-native-htmlview#65]
Unable to install the latest version using npm

using `npm install react-native-htmlview@latest --save ` gets only 0.5.0 version not 0.6.0.

using `npm install react-native-htmlview@0.6.0 --save ` shows error.

**Comment by saberking** [comment]
@ismdcf Version 0.6.0 does not work at all on Mac, I guess that's why it has not been published

**Comment by ismdcf** [comment]
@saberking understood . tried it with the 0.6.0 tag on react native ios and it had issues so rolled back to 0.5.0

**Comment by jsdf** [comment]
latest version should work now
