### ISSUE TITLE
WebView not working with renderNode

### ISSUE THREAD

**Issue by scazzy** [jsdf/react-native-htmlview#68]
I'm trying to extend functionality for adding iframes (youtube videos) etc, but it's throwing an error "Views nested within a <Text> must have a width and height", where infact, the width and height are explicitly mentioned

```
renderNode={(node) => {
  if(node.name === 'iframe') {
    console.log(node);
    const iframeHtml = "<iframe"+ {...node.attribs} +"></iframe>";
    return <WebView key={'node_iframe'} source={{html: iframeHtml}} style={{width: 200, height: 200}} />
  }
}}
```

**Comment by vtisnado** [comment]
+1

**Comment by jsdf** [comment]
Have you tried wrapping your WebView in a View and putting the width & height on the View instead?

**Comment by scazzy** [comment]
@jsdf Tried. So, the problem is the DOM elements are nested. And the width and height are dynamic of the webview.
I have modified your lib for myself tho such that it'll bring all BLOCK view (webview in this case) to root hierarchy instead of making it a children of TEXT component.

**Comment by koenpunt** [comment]
This should be working fine since 07923f8095792d3bc10023421f0335c73d706466
