### ISSUE TITLE
Open local html file

### ISSUE THREAD

**Issue by sun2rise** [jsdf/react-native-htmlview#69]
Hi, i would like if there is a way to open a local html file which loads some local js libs too..
What if i want to host a complete website from inside my app?
Thanks

**Comment by jsdf** [comment]
You should use a [WebView](https://facebook.github.io/react-native/docs/webview.html) if you want to run a complete webpage with Javascript. react-native-htmlview has no intention of supporting that use case.

**Comment by NinoMartino** [comment]
Hi, I need to open a local html file, not a full web page. Can it be done in htmlview? Thanks..

**Comment by isilher** [comment]
Hi @NinoMartino, you should be able to implement a means to extract the contents of a local file, then supply the resulting string as an argument to the component.
