### ISSUE TITLE
<p></p> gets too much space after

### ISSUE THREAD

**Issue by nbastoWM** [jsdf/react-native-htmlview#7]
Hi,

If I have some text like `<p>123</p><p>456</p>` the final result has like 3 or 4 break lines between the two paragraphs.
I tryed to put negative margins and paddings on p tag style but with no success.
Is there any way reduce that space?
Thanks.

**Comment by andue** [comment]
@nbastoWM did you found a solution yet?

**Comment by grittathh** [comment]
Editing line 11 in HTMLView.js will do the trick

**Comment by andue** [comment]
thx @grittathh

**Comment by raphaelvigee** [comment]
This has done the trick :

```
var desc = this.description
            .replace(new RegExp('<p>', 'g'), '<span>')
            .replace(new RegExp('</p>', 'g'), '</span>')
;
```

**Comment by s-ostrovsky** [comment]
@raphaelvigee can you explain your solution? thx

**Comment by raphaelvigee** [comment]
The `p` tags have a `margin-bottom`, replacing them with `span`s made the trick

**Comment by s-ostrovsky** [comment]
@raphaelvigee where should I paste your regexp? thanks a lot!

**Comment by jonolock91** [comment]
If you go into the installed node module package and go to the file `htmlToElement.js` on line 11 you can remove a new line break character `const PARAGRAPH_BREAK = '\n\n';` reducing it to one line - Just note that if you re-install the package it'll be overwritten.

**Comment by gregblass** [comment]
Also, is there any reason why `marginBottom: 20` wouldn't work on a p tag? I could just pass in `addLineBreaks={false}` and control the bottom margin on paragraphs myself and then not have to modify the library code, but for some reason it isn't being applied.

**Comment by jasongrishkoff** [comment]
Encountering this issue as well on my side. The span solution isn't ideal as it causes a whole bunch of other formatting inconsistencies.

**Comment by gregblass** [comment]
There is a parent `Text` component wrapping any child `Text` components in this library. I ended up forking it and re-writing for my use case. IMO its a fairly significant oversight because of the fact that nested Text components in React Native will ignore margins and padding, which cripples your styling options.

**Comment by centotaure** [comment]
Having this issue as well, is an official fix planned ? ( RN 0.44.3 )

**Comment by gregblass** [comment]
I can't speak for the developer here, but I didn't have time to wait around. You could always submit a PR with that extra `Text` element removed. Or fork this repo and use your own. As soon as I get a spare second I may either upload my fork or submit a PR for this. The issue is that I changed a lot of code, so I may just upload my fork to github.

**Comment by isilher** [comment]
From `0.10.0` you can pass your own values for `bullet`, `paragraphBreak`, `lineBreak`, `NodeComponent`, `nodeComponentProps`, `RootComponent`, `rootComponentProps`, `TextComponent` and `textComponentProps`. That should allow for multiple approaches to solve this issue as best fits your use case.

**Comment by zachgibson** [comment]
@isilher or anyone else have an example of how to fix this issue? I tried all of the above to remedy the giant spacing in between p tags to no avail. Using react-native-htmlview@0.12.0 with [Expo](https://expo.io/).

**Comment by richchurcher** [comment]
Just dropping a note here to clarify something I hadn't realised... by killing the default newline-inserting behaviour using `addLineBreaks`, you can actually get pretty decent paragraph spacing:
```
    return (
        <HTMLView
          addLineBreaks={false}
          stylesheet={richTextStyles}
          value={content} />
    )

// ...

const richTextStyles = StyleSheet.create({
  p: {
    marginTop: 3,
    marginBottom: 3
  }
})
```
Not perfect, but a handy workaround.

**Comment by fxhereng** [comment]
What worked for me was to delete break lines from html text: 

```javascript
 htmlText = htmlText.replace(/(\r\n|\n|\r)/gm, '');

[...]

<HTMLView
            stylesheet={htmlStyles}
            addLineBreaks={false}
            value={htmlText}
          />


[...]

const htmlStyles = StyleSheet.create({
  p: {
    marginTop: 5,
    marginBottom: 5
  },
  ul: {
    marginTop: 5,
    marginBottom: 5
  },
  ol: {
    marginTop: 5,
    marginBottom: 5
  }
});


```
