### ISSUE TITLE
Default styling for all the text

### ISSUE THREAD

**Issue by jitenderchand1** [jsdf/react-native-htmlview#70]
We got response in two format. Sometimes we got HTML tag within the response but sometimes we got plain string.

We do styling bases on the tags like given below. I want to apply the styling for all the text whether they are wrapped in HTML tag or not.

`const webViewStyle = StyleSheet.create({
    p: {
      color:"red",
    },
 })`

`const body = "<p>Display Text</p>"`
`const body = "Display Text"`

`<HTMLView style={styles.content} value={subHeader} stylesheet={webViewStyle} />`

**Comment by rajnikantsethiya** [comment]
how to style text in Htmlview, default styling !!!!!
Any solution or alternative to render HTML in react native?

**Comment by stefan-digital-chefs** [comment]
Just do something like this:

`<HTMLView value={"<styledText>"+subHeader+"</styledText>" stylesheet={webViewStyle} />}`

and

`const HTMLViewStyles = StyleSheet.create({
  styledText: {
    color:"red"
  }
});
`

**Comment by rajnikantsethiya** [comment]
Thanks for the reply @stefan-digital-chefs ...
But the solution is not working its not changing the colours for anything.:(

**Comment by seanyesmunt** [comment]
Any update on this? Using `<styledText>` doesn't work for me. I'm wrapping my text in a `<p>` and trying to update the color for that doesn't work either.

**Comment by stefan-digital-chefs** [comment]
Weird. This works for me, just putting an element (for example: <newCustomElement>) around the content string. And then provide a style for that element, like this
`const webViewStyle = StyleSheet.create({ newCustomElement: { color:"red" } });`

**Comment by seanyesmunt** [comment]
Ahh, working good for me now. I wasn't passing in the stylesheet correctly. 

Thanks for the help.

**Comment by richchurcher** [comment]
Props can now be passed to the `Text` component via `textComponentProps`: see updated docs for details. This includes passing the `style` prop :)

**Comment by nitinnavik** [comment]
what happen if value is normal text and we want to apply style for the same text .
eg -
value = 'The Life of Python,<b>TEST</b>'
we can appy style to b tag but how we can apply style to all the text even it not wrap with any html tag
