### ISSUE TITLE
A troubles with imports

### ISSUE THREAD

**Issue by vanekt** [jsdf/react-native-htmlview#74]
When I trying use the latest version (6ed145ae0089860fb9462a203bd2555c2ab43534), the application throws error:
![1488795130742](https://cloud.githubusercontent.com/assets/10152345/23605768/0dbb4916-026f-11e7-92e3-0a66ff8bb9af.jpg)
![1488795164973](https://cloud.githubusercontent.com/assets/10152345/23605776/14d353d8-026f-11e7-89ae-51bbf8ba6577.jpg)

**Comment by jsdf** [comment]
should be fixed now
