### ISSUE TITLE
Error installing newest version (0.7.1)

### ISSUE THREAD

**Issue by colloquet** [jsdf/react-native-htmlview#80]
Hi,

Thanks for making such useful plugin, I was previously using 0.5.0 and tried to update to newest version, however I am getting errors when installing from npm or yarn, here are the screenshots:
![screen shot 2017-03-18 at 5 13 16 pm](https://cloud.githubusercontent.com/assets/6201495/24070750/50df957e-0bfe-11e7-83f7-12bd90442ee7.png)
![screen shot 2017-03-18 at 5 14 03 pm](https://cloud.githubusercontent.com/assets/6201495/24070751/50e0d6d2-0bfe-11e7-94dd-1f6d6a386fb6.png)
Am I doing it correctly? Am I missing something?

Cheers.

**Comment by jsdf** [comment]
looks like yarn publish is buggy https://github.com/yarnpkg/yarn/issues/1959

I've just published 0.7.2 via npm and it seems to be okay. please try installing that version and see if it works for you

**Comment by colloquet** [comment]
Hi,

I can confirm its working now, I was able to install 0.7.2 through npm.

Thanks!
Cheers.
