### ISSUE TITLE
How to support a url with HtmlView?

### ISSUE THREAD

**Issue by panxw** [jsdf/react-native-htmlview#83]
I wan't to use this to react-native-web as WebView, so I ask this question.

**Comment by jsdf** [comment]
do you mean a link like `<a href="something.com">`? That is already supported

**Comment by panxw** [comment]
I mean something like webview.loadUrl(url) in andorid.

**Comment by richchurcher** [comment]
`loadUrl` displays pretty well any URL which I think is outside the scope of this package. Sorry!
