### ISSUE TITLE
Text elements don't support a lot of formatting that Views do

### ISSUE THREAD

**Issue by mark0978** [jsdf/react-native-htmlview#86]
So I tried writing some CSS to style a div and that didn't work well at all.  Started digging into why and find that most everything is a `<Text>` element which does very little when it comes to layout.  I don't know why `<Text>` elements don't do it, but they don't.

So I coded up a simple renderer to compensate for this and show the issue and hope to discuss how to best go forward with a real fix.

```
function myDomElement(node, index, list, parent, origRenderer) {
    console.log(node);
    if(node.name === 'div') {
        return (<View style={ {paddingLeft: 25} }>
                    <Text>{ node.children[0].data }</Text>
                </View>);
    }
    return undefined;
}

-------------
                <HTMLView
                    value={ HTML}
                    stylesheet={ styles }
                    renderNode= { myDomElement }
                />
```

When I surround the `<Text>` element with a `<View>` I can now do things like padding (and borders).  Where the `<Text>` element will ignore those stylings, but will happily accept font specifications.

I'm wondering aloud here if it makes sense to just wrap every `<Text>` in a `<View>` and hand them both the styles for that tag, but I seem to remember `<Text>` being a bit indignant about certain layoutProps so it probably needs a function to divide the styles according to some set of rules.

The real fix is probably for react-native to support all the styling in all the elements but pretty sure that will not fit in my time table too well.

Ideas?  Cautions?  What's a good way to approach this?  I'm fairly new to react-native (less than 10 hours) so I'm hoping someone with some more experience can give me some guidance.

**Comment by mark0978** [comment]
Forgot to mention that styles are not available to the customRenderer either, that's probably a bug, but could be worked out while working thru this formatting problem.

**Comment by richchurcher** [comment]
@mark0978 if you're still interested in this, let me know :smile: there are some related PRs, and a recent change to the library allows passing in a component in place of `Text`.

**Comment by mark0978** [comment]
For my purposes that webview is working.  The htmlview is just a bit too far from the webview for me to use.  Thanks though.
