### ISSUE TITLE
Height CSS not applying

### ISSUE THREAD

**Issue by harish220** [jsdf/react-native-htmlview#87]
Hi,

`<HTMLView value={htmlContent} stylesheet={stylesShortDesc}/>`

and Stylesheet
```
const stylesShortDesc = StyleSheet.create({
  a: {
     height:55,
    color:'#343434', 
    fontSize:13,
    lineHeight:18
  }
```

But HTML view is not rendering with custom **StyleSheet**

**Comment by richchurcher** [comment]
@harish220 By default the `Text` component is used: this does not support styling of height and width (see https://facebook.github.io/react-native/docs/text.html#style for a list of available styles). You can now pass in a component to use in place of `Text` which might allow more flexibility (see updated docs for `TextComponent` and `NodeComponent`).

You can also to some extent control height of an individual link tag using `lineHeight`, if that's of any use to you.
