### ISSUE TITLE
textAlign not working on iOS

### ISSUE THREAD

**Issue by sajjadrad** [jsdf/react-native-htmlview#91]

**Comment by flavordaaave** [comment]
I'm trying to set `textAlign: center` on an `h1`. Setting a `backgroundColor` to the `h1` tag shows that the problem is that the view is not taking the full width. So I tried setting `width: Dimensions.get('window').width` but the `h1` is still NOT taking the full width and not centered.

**Comment by flavordaaave** [comment]
#58 has a working solution

**Comment by richchurcher** [comment]
Closing in favour of #58 .
