### ISSUE TITLE
UL OL not showing correct number

### ISSUE THREAD

**Issue by lordress** [jsdf/react-native-htmlview#92]
Do you know why the generated OL always show even number? eg.below
2. Test
4. Asd.
6. aasdd
8. aaaaa.
10. ddddd

Anybody experience same thing?

**Comment by mismith0227** [comment]
I also experienced the same thing.

Because the value of index is "1, 3, 5, 7, 9 ...", it seems to be "2, 4, 6, 8 ...".
https://github.com/jsdf/react-native-htmlview/blob/master/htmlToElement.js#L88

If we divide by 2 at first aid it will be in order but it will not be a fundamental solution ...?
```
listItemPrefix = `${(index + 1) / 2}. `;
```

**Comment by richchurcher** [comment]
Looks like this was fixed :)

**Comment by Antoine38660** [comment]
Hey, we are using `react-native-htmlview` in [gitpoint/git-point](https://github.com/gitpoint/git-point) and as I said in https://github.com/gitpoint/git-point/issues/92, this issue doesn't seem to be fixed.

@richchurcher on wich version it looks like to be fixed ? :)

----

Screenshot:
<img src="https://user-images.githubusercontent.com/9287184/28253035-b7282c0e-6a74-11e7-8a7c-3774af66e447.jpg" alt="Gitpoint" width="300"/>
Original markdown:
> 1. One
> 2. Two
> 3. Three
> 4. Four
> 5. Five
> 6. ...
