### ISSUE TITLE
onRenderNode not working with image nodes in Android

### ISSUE THREAD

**Issue by CabuxaMapache** [jsdf/react-native-htmlview#94]
I'm getting this error rendering my html: `Nesting of <View> within <Text> is not supported on Android`
The code in my component:

	  _onRenderNode = (node, index, siblings, parent, defaultRenderer) => {
		if (node.name == 'img') {
		  return (
			<Image source={'https://i.redd.it/1l01wjsv22my.jpg'} width={50} height={50} />
		  );
		}
	  }
	  
	  render() {
		let myHtml = "<p><img src=\"https://i.redd.it/1l01wjsv22my.jpg\" width=\"10\" height=\"10\" /></p>";
		return (
		  <HTMLView value={myHtml} renderNode = {this._onRenderNode} />
		);
	  }
```

**Comment by richchurcher** [comment]
I don't... really see what's intended here? You should be able to just do this:
```
  const myHtml = `<img src="https://i.redd.it/1l01wjsv22my.jpg" width="50" height="50">`
  return <HTMLView value={myHtml} />
```
Maybe if this doesn't answer your question, you could provide more detail about what you're trying to accomplish?
